DROP TABLE IF EXISTS users,
    requests,
    items,
    bookings,
    comments;

CREATE TABLE IF NOT EXISTS users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email varchar(150) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests (
  id int generated by default as identity primary key,
  description varchar(300) not null,
  requester_id int not null references users(id) on delete cascade,
  created timestamp without time zone
);

CREATE TABLE IF NOT EXISTS items (
    id INT Generated by default as identity primary key,
    name varchar(100) not null,
    description varchar(300) not null,
    is_available boolean not null,
    owner_id int not null references users(id) on delete cascade,
    request_id bigint references requests(id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id int GENERATED BY DEFAULT  as identity primary key,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    item_id int not null references items(id) on delete cascade,
    booker_id int not null references users(id) on delete cascade,
    status varchar(10) not null
);

create table if not exists comments (
    id int generated by default as identity primary key,
    text varchar(255) not null,
    item_id int not null references items(id) on delete cascade,
    author_id int not null references users(id) on delete cascade,
    created timestamp without time zone
);